from flask import current_app as app


# For reference, the SQL for the Users table is as follows:
# 
# CREATE TABLE Carts (
#     id INT NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
#     userid INT NOT NULL REFERENCES Users(id),
#     quantity INT NOT NULL,
#     sellerinventoryid INT NOT NULL REFERENCES SellerInventories(id)
#     saved_for_later BOOLEAN DEFAULT FALSE
# );

class Cart:
    def __init__(self, id, userid, quantity, sellerinventoryid, saved_for_later):
        self.id = id
        self.userid = userid
        self.quantity = quantity
        self.sellerinventoryid = sellerinventoryid
        self.saved_for_later = saved_for_later

