from flask import current_app as app


# For reference, the SQL for the Users table is as follows:
# 
# CREATE TABLE Carts (
#     id INT NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
#     userid INT NOT NULL REFERENCES Users(id),
#     quantity INT NOT NULL,
#     sellerinventoryid INT NOT NULL REFERENCES SellerInventories(id)
#     saved_for_later BOOLEAN DEFAULT FALSE
# );

# CREATE TABLE PriceHistory (
#     id INT NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
#     price DECIMAL(12,2) NOT NULL,
#     time_changed timestamp without time zone NOT NULL DEFAULT (current_timestamp AT TIME ZONE 'UTC')
# );

# CREATE TABLE Products (
#     id INT NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
#     categoryid INT NOT NULL REFERENCES Categories(id),
#     name VARCHAR(255) UNIQUE NOT NULL,
#     description VARCHAR(511),
#     image VARCHAR(255)
# );

# CREATE TABLE SellerInventories (
#     id INT NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
#     sellerid INT NOT NULL REFERENCES Users(id),
#     productid INT NOT NULL REFERENCES Products(id),
#     priceid INT NOT NULL REFERENCES PriceHistory(id),
#     quantity INT NOT NULL CHECK (quantity >= 0)
# );

class Cart:
    def __init__(self, id, userid, quantity, sellerinventoryid, saved_for_later):
        self.id = id
        self.userid = userid
        self.quantity = quantity
        self.sellerinventoryid = sellerinventoryid
        self.saved_for_later = saved_for_later


    @staticmethod
    def get_all_by_uid(uid, saved_for_later=False):
        rows = app.db.execute('''
SELECT p.name, p.image, ph.price, c.quantity
FROM Carts c
JOIN SellerInventories si ON c.sellerinventoryid = si.id
JOIN Products p ON si.productid = p.id
JOIN PriceHistory ph ON ph.id = (
    SELECT ph2.id
    FROM PriceHistory ph2
    WHERE ph2.id = si.priceid
    ORDER BY ph2.time_changed DESC
    LIMIT 1
)
WHERE c.userid = :uid AND c.saved_for_later = :saved_for_later;
''',
                              uid=uid,
                              saved_for_later=saved_for_later)
        # Create a list of dictionaries for each row in the query result
        cart_items = [{'name': row[0], 'image': row[1], 'price': row[2], 'quantity': row[3]} for row in rows]
        return cart_items
