from flask import current_app as app

# For reference, the SQL for the Users table is as follows:
# 
# CREATE TABLE Categories (
#     id INT NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
#     name VARCHAR(255) UNIQUE NOT NULL,
# );

class Category:
    def __init__(self, id, name):
        self.id = id
        self.name = name
