from flask import current_app as app

# For reference, the SQL for the Users table is as follows:
# 
# CREATE TABLE Coupons (
#     id INT NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
#     sellerinventoryid INT NOT NULL REFERENCES SellerInventories(id),
#     code VARCHAR UNIQUE NOT NULL,
#     discount DECIMAL(3,2) NOT NULL CHECK (discount >= 0 AND discount <= 100),
# );

class Coupon:
    def __init__(self, id, sellerinventoryid, code, discount):
        self.id = id
        self.sellerinventoryid = sellerinventoryid
        self.code = code
        self.discount = discount
