from flask import current_app as app


# For reference, the SQL for the Users table is as follows:
# 
# CREATE TABLE Orders (
#     id INT NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
#     userid INT NOT NULL REFERENCES Users(id),
#     time_brought timestamp without time zone NOT NULL DEFAULT (current_timestamp AT TIME ZONE 'UTC'),
#     order_status VARCHAR(255) NOT NULL
# );

class Order:
    def __init__(self, id, userid, time_brought, order_status):
        self.id = id
        self.userid = userid
        self.time_brought = time_brought
        self.order_status = order_status


    @staticmethod
    def get_all_by_uid_since(uid, since):
        rows = app.db.execute('''
SELECT id, userid, time_brought, order_status
FROM Orders
WHERE userid = :uid
AND time_brought >= :since
ORDER BY time_brought DESC
''',
                              uid=uid,
                              since=since)
        return [Order(*row) for row in rows]