from flask import current_app as app

# For reference, the SQL for the Users table is as follows:
# 
# CREATE TABLE OrderItems (
#     id INT NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
#     orderid INT NOT NULL REFERENCES Orders(id),
#     productid INT NOT NULL REFERENCES Products(id),
#     sellerid INT NOT NULL REFERENCES Users(id),
#     quantity INT NOT NULL,
#     brought_price DECIMAL(12,2) NOT NULL,
#     fulfilled BOOLEAN DEFAULT FALSE
# );

class OrderItem:
    def __init__(self, id, orderid, productid, sellerid, quantity, brought_price, fulfilled):
        self.id = id
        self.orderid = orderid
        self.productid = productid
        self.sellerid = sellerid
        self.quantity = quantity
        self.brought_price = brought_price
        self.fulfilled = fulfilled

    @staticmethod
    def get_user_purchases(user_id):
        query = """
        SELECT 
            P.name AS product_name,
            OI.quantity,
            OI.brought_price,
            O.time_brought AS order_time,
            O.order_status
        FROM Orders O
        JOIN OrderItems OI ON O.id = OI.orderid
        JOIN Products P ON OI.productid = P.id
        WHERE O.userid = :user_id
        ORDER BY O.time_brought DESC;
        """
        rows = app.db.execute(query, user_id=user_id)
        purchase_items = [{'product_name': row[0], 'quantity': row[1], 'brought_price': row[2], 'order_time': row[3], 'order_status':row[4]} for row in rows]
        return purchase_items
    