from flask import current_app as app

# For reference, the SQL for the Users table is as follows:
# 
# CREATE TABLE OrderItems (
#     id INT NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
#     orderid INT NOT NULL REFERENCES Orders(id),
#     productid INT NOT NULL REFERENCES Products(id),
#     sellerid INT NOT NULL REFERENCES Users(id),
#     quantity INT NOT NULL,
#     brought_price DECIMAL(12,2) NOT NULL,
#     fulfilled BOOLEAN DEFAULT FALSE
# );

class OrderItem:
    def __init__(self, id, orderid, productid, sellerid, quantity, brought_price, fulfilled):
        self.id = id
        self.orderid = orderid
        self.productid = productid
        self.sellerid = sellerid
        self.quantity = quantity
        self.brought_price = brought_price
        self.fulfilled = fulfilled
