from flask import current_app as app

# For reference, the SQL for the Users table is as follows:
# 
# CREATE TABLE PriceHistory (
#     id INT NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
#     inventoryid INT NOT NULL REFERENCES SellerInventories(id),
#     price DECIMAL(12,2) NOT NULL,
#     time_changed timestamp without time zone NOT NULL DEFAULT (current_timestamp AT TIME ZONE 'UTC')
# );

class PriceHistory:
    def __init__(self, id, inventoryid, price, time_changed):
        self.id = id
        self.inventoryid = inventoryid
        self.price = price
        self.time_changed = time_changed
