from flask import current_app as app

# For reference, the SQL for the Users table is as follows:
# 
# CREATE TABLE Products (
#     id INT NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
#     categoryid INT NOT NULL REFERENCES Categories(id),
#     name VARCHAR(255) UNIQUE NOT NULL,
#     description VARCHAR(511),
#     image VARCHAR(255),
# );

class Product:
    def __init__(self, id, categoryid, name, description, image):
        self.id = id
        self.categoryid = categoryid
        self.name = name
        self.description = description
        self.image = image

    @staticmethod
    def get(id):
        rows = app.db.execute('''
SELECT id, name, price, available
FROM Products
WHERE id = :id
''',
                              id=id)
        return Product(*(rows[0])) if rows is not None else None

    @staticmethod
    def get_all():
        rows = app.db.execute('''
SELECT *
FROM Products
''',)
        return [Product(*row) for row in rows]
