from flask import current_app as app

# For reference, the SQL for the Users table is as follows:
# 
# CREATE TABLE ProductComments (
#     id INT NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
#     productid INT NOT NULL REFERENCES Products(id),
#     userid INT NOT NULL REFERENCES Users(id),
#     comment VARCHAR(255),
#     time_commented timestamp without time zone NOT NULL DEFAULT (current_timestamp AT TIME ZONE 'UTC'),
#     rate INT
# );


class ProductComment:
    def __init__(self, id, productid, userid, comment, time_commented, rate):
        self.id = id
        self.productid = productid
        self.userid = userid
        self.comment = comment
        self.time_commented = time_commented
        self.rate = rate
