from flask import current_app as app

# For reference, the SQL for the Users table is as follows:
# 
# CREATE TABLE ProductComments (
#     id INT NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
#     productid INT NOT NULL REFERENCES Products(id),
#     userid INT NOT NULL REFERENCES Users(id),
#     comment VARCHAR(255),
#     time_commented timestamp without time zone NOT NULL DEFAULT (current_timestamp AT TIME ZONE 'UTC'),
#     rate INT
# );


class ProductComment:
    def __init__(self, id, productid, userid, comment, time_commented, rate):
        self.id = id
        self.productid = productid
        self.userid = userid
        self.comment = comment
        self.time_commented = time_commented
        self.rate = rate

    @staticmethod
    def get_product_comments_by_user(userid):
        sqlstr = """
        SELECT comment, rate, time_commented, productid
        FROM ProductComments
        WHERE userid = :userid
        ORDER BY time_commented DESC
        LIMIT 5;
        """
        results = app.db.execute(sqlstr, userid=userid)
        comments = [{'comment': row[0], 'rate': row[1],
                     'time_commented': row[2],
                     'productid': row[3]
                     } for row in results]
        return comments



    @staticmethod
    def insert_comment(comment, product_id, rating, user_id):
        sqlstr = """
        INSERT INTO ProductComments (productid, userid, comment, rate, time_commented) 
        VALUES (:product_id, :user_id, :comment, :rating, date_trunc('second', current_timestamp));
        """
        results = app.db.execute(sqlstr, product_id=product_id, user_id=user_id, comment=comment, rating=rating)
   

