from flask import current_app as app

# For reference, the SQL for the Users table is as follows:
# 
# CREATE TABLE SellerInventories (
#     id INT NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
#     sellerid INT NOT NULL REFERENCES Users(id),
#     productid INT NOT NULL REFERENCES Products(id),
#     priceid INT NOT NULL REFERENCES PriceHistory(id),
#     quantity INT NOT NULL CHECK (quantity >= 0)
# );

class SellerInventory:
    def __init__(self, id, sellerid, productid, priceid, quantity):
        self.id = id
        self.sellerid = sellerid
        self.productid = productid
        self.priceid = priceid
        self.quantity = quantity
