from flask import current_app as app

# For reference, the SQL for the Users table is as follows:
# 
# CREATE TABLE SellerComments (
#     id INT NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
#     userid INT NOT NULL REFERENCES Users(id),
#     sellerid INT NOT NULL REFERENCES Users(id),
#     comment VARCHAR(255),
#     date_commented timestamp without time zone NOT NULL DEFAULT (current_timestamp AT TIME ZONE 'UTC'),
#     rate INT
# );

class SellerComment:
    def __init__(self, id, userid, sellerid, comment, date_commented, rate):
        self.id = id
        self.userid = userid
        self.sellerid = sellerid
        self.comment = comment
        self.date_commented = date_commented
        self.rate = rate
